theme: jekyll-theme-minimal
logo:https://www.google.com.hk/url?sa=i&url=https%3A%2F%2Fsingularityhub.com%2F2020%2F04%2F27%2Fthis-new-smartphone-based-dna-test-could-help-track-disease-in-real-time%2F&psig=AOvVaw2r1qJTe14TmyycdT9bjrEU&ust=1638556002315000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMj50fnexfQCFQAAAAAdAAAAABAJ
title: Bioinformatics Class
